# Generated by Django 3.2.5 on 2021-07-17 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(choices=[('CUR', 'Currently Taking'), ('PAS', 'No Longer Taking')], default='CUR', max_length=3, null=True)),
                ('prescriber', models.CharField(blank=True, max_length=255)),
                ('dosage', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('label_img', models.ImageField(blank=True, null=True, upload_to='medications/')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
