# Generated by Django 3.2.5 on 2021-07-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='toothbrush_replaced',
            field=models.DateField(blank=True, null=True),
        ),
    ]
