# Generated by Django 3.2.5 on 2021-07-11 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_profile_toothbrush_replaced'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dentist',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
