# Generated by Django 3.2.5 on 2021-07-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='appt_img',
            field=models.ImageField(null=True, upload_to='appointment_img/'),
        ),
    ]
