# Generated by Django 3.2.5 on 2021-07-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_alter_record_appt_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='appt_img',
            field=models.ImageField(blank=True, null=True, upload_to='appointment_img/'),
        ),
    ]
